config/routes.rb
IntentPizza::Application.routes.draw do

  resources :users
  resource :account, :controller => "users"
  resources :pizzas do
    member do
      get 'order'
    end
    
    resources :toppings
  end
  
  resource :user_sessions
  
  match 'logout' => 'user_sessions#destroy'
  
  root :to => 'user_sessions#new'

end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
  has_many :toppings
  belongs_to :user
  
  def order
    self.ordered = true
    self.save!
  end
end

app/models/topping.rb
class Topping < ActiveRecord::Base
  belongs_to :pizza
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :pizzas
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
  
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end
  
    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end
 
    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end
    
    def store_location
      session[:return_to] = request.request_uri
    end
    
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_filter :require_user
  # GET /pizzas
  # GET /pizzas.xml
  def index
    @pizzas = current_user.pizzas

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pizzas }
    end
  end

  # GET /pizzas/1
  # GET /pizzas/1.xml
  def show
    @pizza = Pizza.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pizza }
    end
  end

  # GET /pizzas/new
  # GET /pizzas/new.xml
  def new
    @pizza = Pizza.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pizza }
    end
  end

  # GET /pizzas/1/edit
  def edit
    @pizza = Pizza.find(params[:id])
  end

  # POST /pizzas
  # POST /pizzas.xml
  def create
    @pizza = Pizza.new(params[:pizza])
    @pizza.user_id = current_user.id

    respond_to do |format|
      if @pizza.save
        flash[:notice] = 'Pizza was successfully created.'
        format.html { redirect_to(@pizza) }
        format.xml  { render :xml => @pizza, :status => :created, :location => @pizza }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pizza.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pizzas/1
  # PUT /pizzas/1.xml
  def update
    @pizza = Pizza.find(params[:id])

    respond_to do |format|
      if @pizza.update_attributes(params[:pizza])
        flash[:notice] = 'Pizza was successfully updated.'
        format.html { redirect_to(@pizza) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pizza.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.xml
  def destroy
    @pizza = Pizza.find(params[:id])
    @pizza.destroy

    respond_to do |format|
      format.html { redirect_to(pizzas_url) }
      format.xml  { head :ok }
    end
  end
  
  def order
    @pizza = Pizza.find(params[:id])
    @pizza.order
    redirect_to(pizzas_url)
  end
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  before_filter :require_user
  # GET /toppings
  # GET /toppings.xml
  def index
    @pizza = Pizza.find(params[:pizza_id])
    @toppings = @pizza.toppings

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @toppings }
    end
  end

  # GET /toppings/1
  # GET /toppings/1.xml
  def show
    @topping = Topping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topping }
    end
  end

  # GET /toppings/new
  # GET /toppings/new.xml
  def new
    @topping = Topping.new
    @pizza = Pizza.find(params[:pizza_id])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topping }
    end
  end

  # GET /toppings/1/edit
  def edit
    @topping = Topping.find(params[:id])
  end

  # POST /toppings
  # POST /toppings.xml
  def create
    @topping = Topping.new(params[:topping])
    @topping.pizza_id = params[:pizza_id]

    respond_to do |format|
      if @topping.save
        flash[:notice] = 'Topping was successfully created.'
        format.html { redirect_to(pizza_path(params[:pizza_id])) }
        format.xml  { render :xml => @topping, :status => :created, :location => @topping }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topping.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /toppings/1
  # PUT /toppings/1.xml
  def update
    @topping = Topping.find(params[:id])

    respond_to do |format|
      if @topping.update_attributes(params[:topping])
        flash[:notice] = 'Topping was successfully updated.'
        format.html { redirect_to(@topping) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topping.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /toppings/1
  # DELETE /toppings/1.xml
  def destroy
    @topping = Topping.find(params[:id])
    @topping.destroy

    respond_to do |format|
      flash[:notice] = 'Topping removed from the pizza.'
      format.html { redirect_to(pizza_toppings_url(Pizza.find(params[:pizza_id]))) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  #before_filter :require_no_user, :only => [:new, :create]
  #before_filter :require_user, :only => :destroy
  
  def new
    logger.info "Creating a new user session"
    @user_session = UserSession.new 
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end
 
  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intent Pizza</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
</head>
<body>
<img src="/images/intent_pizza_logo.jpg">

<%= yield %>

</body>
</html>

app/views/pizzas/edit.html.erb
<h1>Editing pizza</h1>

<% form_for(@pizza) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

app/views/pizzas/index.html.erb
<h1>Listing pizzas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Number of toppings</th>
    <th>Order placed?</th>
  </tr>

<% @pizzas.each do |pizza| %>
  <tr>
    <td><%=h pizza.name %></td>
    <td><%=h pizza.size %></td>
    <td><%= pizza.toppings.size %></td>
    <td><%= pizza.ordered? %>
    <td><%= link_to 'Show', pizza %></td>
    <% unless pizza.ordered? %>
      <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
      <td><%= link_to 'Remove', pizza, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Place another order', new_pizza_path %>

app/views/pizzas/new.html.erb
<h1>New pizza</h1>

<% form_for(@pizza) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

app/views/pizzas/show.html.erb
<p>
  <b>Name:</b>
  <%=h @pizza.name %>
</p>

<p>
  <b>Size:</b>
  <%=h @pizza.size %>
</p>

<p>
  <b>Toppings:</b>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Double order</th>
  </tr>

<% @pizza.toppings.each do |topping| %>
  <tr>
    <td><%=h topping.name %></td>
    <td><%=h topping.double_order %></td>
    <% unless @pizza.ordered? %>
      <td><%= link_to 'Remove', pizza_topping_path(@pizza, topping), :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<% unless @pizza.ordered? %>
  <p>
    <%= link_to 'Add toppings', new_pizza_topping_path(@pizza)%> || <%= link_to 'Order this pizza', order_pizza_path %>
  </p>
<% end %>

<p>
  <%= link_to 'All orders', pizzas_path %>
</p>

app/views/toppings/new.html.erb
<h1>New topping</h1>

<% form_for(@topping, :url => pizza_toppings_path(@pizza)) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :double_order %><br />
    <%= f.check_box :double_order %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_for @user_session do |f| %>
  <% if @user_session.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited:</h2>
    <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>
 
<p>
  <%= link_to "Create a new user", new_user_path %>
</p>

app/views/users/_form.html.erb
<%= form.label :email %><br />
<%= form.text_field :email %><br />
<br />
<%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
<%= form.password_field :password %><br />
<br />
<%= form.label :password_confirmation %><br />
<%= form.password_field :password_confirmation %><br />

app/views/users/edit.html.erb
<h1>Edit My Account</h1>
 
<% form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>
 
<br /><%= link_to "My Profile", account_path %>

app/views/users/new.html.erb
<h1>Register</h1>
 
<% form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<p>
  <b>Login:</b>
  <%=h @user.email %>
</p>

<p>
  <%= link_to 'Order a pizza', new_pizza_path %>
</p>
 
<p>
  <%= link_to 'Show ordered pizzas', pizzas_path %>
</p>
 
<%= link_to 'Edit', edit_account_path %>